# Generated by Django 3.0.7 on 2020-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alertsdb_snapsdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapsdb',
            name='snap',
            field=models.CharField(max_length=100000),
        ),
    ]
