# Generated by Django 3.0.7 on 2020-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20200713_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapsdb',
            name='snap',
            field=models.CharField(max_length=300000),
        ),
    ]
