# Generated by Django 3.0.7 on 2020-07-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20200721_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camdb',
            old_name='cam_group',
            new_name='group',
        ),
    ]
