# Generated by Django 3.0.7 on 2020-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20200721_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camdb',
            old_name='cam_url',
            new_name='cam_address',
        ),
    ]
