# Generated by Django 3.0.7 on 2020-08-07 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20200807_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsdb',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
