# Generated by Django 3.0.7 on 2020-08-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alertsdb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertsdb',
            name='date',
        ),
    ]
