# Generated by Django 3.0.7 on 2020-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_remove_alertsdb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='camTransformationMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_address', models.CharField(max_length=300)),
                ('transformationMatrix', models.CharField(max_length=1000)),
            ],
        ),
    ]
