# Generated by Django 3.0.7 on 2020-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_camtransformationmatrix_distancethresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReportDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_seconds', models.CharField(max_length=40)),
                ('spotted_on', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=20)),
                ('occurrence', models.CharField(max_length=6)),
                ('severity', models.CharField(max_length=10)),
                ('track_history', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=800)),
            ],
        ),
    ]
