# Generated by Django 3.0.7 on 2020-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_incidentreportdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreportdb',
            name='current_status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
